---
title: "Consumer Complaints Analysis"
author: "I. Banarov, M. Parravani, H. Fang Cai, A. Biagi"
date: "February 4, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

```{r}
library(tm)
library(stopwords)
library(ggplot2)
library(topicmodels)
library(githubinstall)
devtools::install_github('okugami79/sentiment140')
library(sentimentr)
library(dplyr)
source("https://bioconductor.org/biocLite.R")
biocLite("Rgraphviz")
library(graph)
library(Rgraphviz)
library(wordcloud)
pacman::p_load_gh("trinker/textstem")
pacman::p_load(textstem, dplyr)

```

## Import Data & Profile
```{r}
df = read.csv(file.choose(), nrows=200000) #import only subset of data as file is massive
head(df)
summary(df)
str(df)

```

```{r}

ggplot(data=df,mapping=aes(x=reorder(Product,-table(Product)[Product]))) + geom_bar(colour="black", fill="white")+
  xlab("Product")+ylab("Number Complaints")+coord_flip()
  
```
Only a few products have sufficient data for building a classification model. We'll continue with Mortgage through Consumer Loan, then call the rest "Other Product"

```{r}
## Consolidate Product label
ProductList<- c("Mortgage", "Debt collection", "Credit reporting", "Credit card", "Bank account or service", "Student loan", "Consumer Loan")
df %>%
  select(Product, Complaint.ID) %>%
  group_by(df$Product) %>%
  summarise(Complaint_count = n()) %>%
  arrange(desc(Complaint_count))

#Not sure why this doesn't work. I found it on stackoverflow, and adapted it. I use gsub line by line below instead
transform(df,Product = factor(replace(as.character(Product),list = !Product %in% ProductList,values = "Other Product")))


df$Product<- gsub("Credit reporting, credit repair services, or other personal consumer reports", "Other Product", df$Product)
df$Product<- gsub("Payday loan", "Other Product", df$Product)
df$Product<- gsub("Money transfers", "Other Product", df$Product)
df$Product<- gsub("Checking or savings account", "Other Product", df$Product)
df$Product<- gsub("Credit card or prepaid card", "Other Product", df$Product)
df$Product<- gsub("Other financial service", "Other Product", df$Product)
df$Product<- gsub("Vehicle loan or lease", "Other Product", df$Product)
df$Product<- gsub("Money transfer, virtual currency, or money service", "Other Product", df$Product)
df$Product<- gsub("Payday loan, title loan, or personal loan", "Other Product", df$Product)
df$Product<- gsub("Virtual currency", "Other Product", df$Product)
df$Product<- gsub("Student loan", "Other Product", df$Product)
df$Product<- gsub("Consumer Loan", "Other Product", df$Product)
df$Product<- gsub("Prepaid card", "Other Product", df$Product)
df$Product<- gsub("Other Complaint, title loan, or personal loan", "Other Product", df$Product)

df %>%
  select(Product, Complaint.ID) %>%
  group_by(df$Product) %>%
  summarise(Complaint_count = n()) %>%
  arrange(desc(Complaint_count))
```
```{r results='hide'}
#Transfer Product and Complaint description to another dataframe for processing

df2<-select(df, Product, Consumer.complaint.narrative)
colnames(df2)[2]<-"Complaint"





```

```{r  echo=T, results='hide'}
## Process Text

#Stemm and lemmatize words
df2$Complaint<-as.character(df2$Complaint)
stem_words(df2$Complaint)
lemmatize_words(df2$Complaint)

```
```{r}
#Make Bag of Words
myCorpus <- Corpus(VectorSource(df2$Complaint))

# remove numbers, punctuation and whitespace
myCorpus <- tm_map(myCorpus, removeNumbers)
myCorpus <- tm_map(myCorpus, removePunctuation)
myCorpus <- tm_map(myCorpus, stripWhitespace)
# remove stopwords
# keep "r" by removing it from stopwords
library(stopwords)
myStopwords <- c(stopwords(language="en", source="smart"), "available", "via", "the")

myCorpus <- tm_map(myCorpus, removeWords, myStopwords)

```





